# coding=utf-8

"""
Django settings for siaa project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _

# Construye el path de la aplicación
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Configuraciones globales
NUMERO_ITEMS_PAGINA = 20
AUTH_USER_MODEL = 'seguridad.Usuario'
ROOT_URLCONF = 'siaa.urls'
WSGI_APPLICATION = 'siaa.wsgi.application'
SECRET_KEY = 'vrcj873n@3!vn&7$&6(ha^c_wmo9+4h+#a8*rjrom(w80+%m8j'
DEFAULT_CHARSET = 'utf-8'
LOGIN_URL= '/autenticacion/iniciar-sesion'

# Definición de las app
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    # apps de terceros
    'corsheaders',
    'guardian',
    'django_celery_beat',
    #apps del siaaf
    'app.autenticacion',
    'app.academico',
    'app.bienes',
    'app.bsg',
    'app.cientifica',
    'app.configuracion',
    'app.core',
    'app.curricular',
    'app.edificios',
    'app.hveterinario',
    'app.organico',
    'app.planificacion',
    'app.recaudacion',
    'app.reporte',
    'app.seguridad',
    'app.seguridad_informacion',
    'app.talento_humano',
    'app.tesoreria',
    'app.tributacion',
    'app.unesco',
]

# Autenticacción y seguridad
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # default
    'guardian.backends.ObjectPermissionBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'app.seguridad.utils.username.RequestMiddleware',
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
    {'NAME': 'app.autenticacion.validators.PasswordCedulaValidator', },
]

# Configuración de los Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': ['app.core.templatetags.core_tags'],
        },
    },
]

# Servicios RestFramework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
   'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# Internationalization
LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_L10N = True
# USE_TZ = True
LANGUAGES = (
    ('es', _('spanish')),
    ('en', _('english')),
)

# Archivos estaticos (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale")
]

# Configuracion con Google
GOOGLE_DOMAIN = 'unl.edu.ec'
GOOGLE_CLIENT_EMAIL =  '146743989419-8fgs96l1oqk2n5vrned4up4e20k6c51d.apps.googleusercontent.com'
GOOGLE_PATH_TO_KEYFILE = "SIAA-b09f820b4bc6.p12"
GOOGLE_CLIENT_SECRET =  'rVXyIfDnFoh0T6HWPIkWBVXT'
GOOGLE_SUB_USER = 'siaaf@unl.edu.ec'  # Email of a superuser on your domain
GOOGLE_APPLICATION_NAME = 'siaaf'  # As listed in Google Developers Console
GOOGLE_CLIENT_SECRET_FILE = 'client_secret.json'
CORS_ORIGIN_ALLOW_ALL = True

# Sac, recuperación de la contraseña LDAP
SAC_URL = 'https://sac.unl.edu.ec'

# Configuración de LDAP
LDAP_SERVER = 'ldap.unl.edu.ec'
LDAP_AUTH = 'cn=admin,dc=unl,dc=edu,dc=ec'
LDAP_KEY = 'j8J6gc6GJ45fGHks3bv'
LDAP_OU_BASE = 'ou=personal,dc=unl,dc=edu,dc=ec'
LDAP_OU_DEFAULT = 'ou=otros,' + LDAP_OU_BASE
LDAP_OU_ESTUDIANTE = 'ou=estudiantes,ou=academicos,' + LDAP_OU_BASE
#LDAP_OU_FUNCIONARIO = 'ou=servidores,au=administrativos,' + LDAP_OU_DEFAULT
LDAP_OU_DOCENTE = 'ou=docentes,ou=academicos,' + LDAP_OU_BASE
LDAP_OU_ADMINISTRATIVO  = 'ou=servidores,ou=administrativos,' + LDAP_OU_BASE
LDAP_OU_TRABAJADOR = 'ou=trabajadores,ou=administrativos,' + LDAP_OU_BASE
LDAP_OU_GRUPO = 'ou=grupos,' + LDAP_OU_BASE

# Seguridad en el cierre de sesiones
SESSION_COOKIE_AGE = 86400 #Tiempo de vida de la sesión en segundos (1 día, default 2 semanas)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True #Si sale del navegador, cerrar sesión
