from enum import Enum


class EnumDetalleParametrizacion(Enum):
    USUARIO_BSG = 'USUARIO_BSG'
    INSTITUCION_BSGRC = "INSTITUCION_BSG_REGISTROCIVIL"
    AGENCIA_BSGRC = "AGENCIA_BSG_REGISTROCIVIL"
    USUARIO_BSGRC = "USUARIO_BSG_REGISTROCIVIL"
    CLAVE_BSGRC = "CLAVE_BSG_REGISTROCIVIL"
    USUARIO_BSGMSP = "USUARIO_BSG_MSP"
    CLAVE_BSGMSP = "CLAVE_BSG_MSP"




