from django.conf.urls import url

from . import views
app_name = 'talento_humano'
urlpatterns = [
    ##################
    # Inicio de refactorizar
    ##################
    url(r'^$', views.index, name='index'),
    url(r'^agregarproduccioncientifica/(\d+)$', views.agregar_produccion_cientifica,name='funcionarios.funcionario.agregar_produccion_cientifica'),
    url(r'^asignacion-puestos/asignar_puesto/$', views.asignar_puesto, name='asignacion_puestos.asignar_puesto'),
    url(r'^asignacion-puestos/asignar_puesto_funcionario/(\d+)$', views.asignar_puesto_funcionario,name='asignacion_puestos.asignar_puesto_funcionario'),
    url(r'^asignacion-puestos/funcionario/(\d+)$', views.asignacion_de_puestos, name='asignacion_puestos.funcionario'),
    url(r'^asignacion-puestos/funcionario/asignacion-puesto/editar/(\d+)$', views.editar_asignacion_puesto, name='asignacion_puestos.funcionario.editar'),
    url(r'^asignacion-puestos/funcionario/eliminar/(\d+)$', views.eliminar_asignacion_puesto, name='asignacion_puestos.funcionario.eliminar'),
    url(r'^asignacion-puestos/funcionario/terminacion/(\d+)$', views.terminacion_asignacion_puesto, name='asignacion_puestos.funcionario.terminacion'),
    url(r'^asignacion-puestos/funcionario/renovacion/(\d+)$', views.renovacion_asignacion_puesto, name='asignacion_puestos.funcionario.renovacion'),
    url(r'^asignacion-puestos/funcionario/cambio/(\d+)$', views.cambio_asignacion_puesto, name='asignacion_puestos.funcionario.cambio'),
    url(r'^asignacion-puestos/funcionario/registro/(\d+)/(\d+)$', views.registrar_cambio_asignacion_puesto, name='asignacion_puestos.funcionario.cambio.registrar'),
    url(r'^asignacion-puestos/funcionario/validar/(\d+)$', views.validar_asignacion_puesto, name='asignacion_puestos.funcionario.validar'),
    url(r'^asignacion-puestos/funcionario/fijar-vigente/(\d+)$', views.fijar_vigente_asignacion_puesto, name='asignacion_puestos.funcionario.fijar_vigente'),
    url(r'^asignacion-puestos/lista/$', views.listar_asignar_puesto, name='asignacion_puestos.lista'),
    url(r'^asignacion-puestos/lista/buscar$', views.buscar_asignacion_puestos, name='asignacion_puestos.lista.buscar'),
    url(r'^asignacion-puestos/lista/verificar-vigencia$', views.verificar_vigencia_listar_asignar_puesto, name='asignacion_puestos.lista.verficar_vigemcia'),
    url(r'^ausentismos$', views.listar_ausentismos, name='ausentismos.index'),
    url(r'^ausentismos/buscar$', views.buscar_ausentismos, name='ausentismos.buscar'),
    url(r'^ausentismos/funcionario/(\d+)$', views.ausentismo_funcionario, name='ausentismos.funcionario'),
    url(r'^ausentismos/funcionario/registrar/(\d+)/(\d+)$', views.ausentismo_funcionario_registrar, name='ausentismos.funcionario.registrar'),
    url(r'^ausentismos/eliminar/(\d+)/(\d+)$', views.eliminar_ausentismo, name='ausentismo.eliminar'),
    url(r'^funcionarios$', views.funcionarios, name='funcionarios.index'),
    url(r'^funcionario/reportes$', views.funcionario_reportes, name='funcionario.reportes'),
    url(r'^funcionario/reportes/sniese/(?P<tipo>[\d]+)/$', views.reporte_sniese, name='funcionario.reportes.sniese'),
    url(r'^funcionario/reportes/sniese/generar$', views.generar_reporte_sniese, name='generar.reportes.sniese'),
    url(r'^funcionarios/buscar$', views.funcionarios, name='funcionarios.busqueda'),
    url(r'^funcionarios/fotografias/$', views.cargar_fotografias, name='funcionarios.fotografias'),
    url(r'^funcionarios/funcionario/(\d+)$', views.funcionario, name='funcionarios.funcionario'),
    url(r'^funcionarios/funcionario/uaa_puesto/(\d+)/(\d+)$', views.funcionario_uaa_puesto, name='funcionarios.funcionario.uaa_puesto'),
    url(r'^funcionarios/funcionario/ver_uaa/(\d+)$', views.funcionario_ver_uaa, name='funcionarios.funcionario.ver_uaa'),
    url(r'^funcionarios/funcionario/actualizar/bsg/(\d+)$', views.actualizar_informacion_bsg, name='funcionarios.funcionario.actualizar.bsg'),
    url(r'^funcionarios/funcionario/agregar$', views.agregar_funcionario, name='funcionarios.funcionario.agregar'),
    url(r'^funcionarios/funcionario/agregar/manual$', views.agregar_funcionario_manual, name='funcionarios.funcionario.agregar_manual'),
    url(r'^funcionarios/funcionario/validar_email/(\d+)$', views.validar_email, name='funcionarios.funcionario.validar_email'),
    url(r'^funcionarios/funcionario/vincular$', views.vincular_usuario_funcionario,name='funcionarios.funcionario.vincular'),
    url(r'^funcionarios/funcionario/usuario$', views.funcionario_usuario, name='funcionarios.funcionario.usuario'),
    url(r'^puestos$', views.puestos, name='puestos.index'),
    url(r'^puestos/buscar$', views.buscar_puestos, name='puestos.busqueda'),
    url(r'^puestos/puesto/(\d+)$', views.puesto, name='puestos.puesto'),
    url(r'^puestos/puesto/agregar$', views.agregar_puesto, name='puestos.puesto.agregar'),
    url(r'^puestos/puesto/agregar/actividad/(\d+)$', views.agregar_actividad,name='puestos.puesto.agregar.actividad'),
    url(r'^puestos/puesto/agregar/conocimiento/(\d+)$', views.agregar_conocimiento,name='puestos.puesto.agregar.conocimiento'),
    url(r'^puestos/puesto/agregar/destreza/(\d+)$', views.agregar_destreza,name='puestos.puesto.agregar.destreza'),
    url(r'^puestos/puesto/editar/(\d+)$', views.editar_puesto, name='puestos.puesto.editar'),
    url(r'^puestos/puesto/eliminar/actividad/(\d+)$', views.eliminar_actividad,name='puestos.puesto.eliminar.actividad'),
    url(r'^puestos/puesto/eliminar/conocimiento/(\d+)$', views.eliminar_conocimiento,name='puestos.puesto.eliminar.conocimiento'),
    url(r'^puestos/puesto/eliminar/destreza/(\d+)$', views.eliminar_destreza,name='puestos.puesto.eliminar.destreza'),
    url(r'^regimen-laboral/$', views.regimen_laboral, name='regimen_laboral.index'),
    url(r'^regimen-laboral/buscar$', views.regimen_laboral_buscar, name='regimen_laboral.buscar'),
    url(r'^regimen-laboral/filtro/(\d+)$', views.regimen_laboral_filtro, name='regimen_laboral.filtro'),
    url(r'^regimen-laboral/filtro/(\d+)/buscar$', views.regimen_laboral_filtro, name='regimen_laboral.filtro.buscar'),
    url(r'^reporte/index', views.index_reporte, name='reporte.form'),
    url(r'^reporte/vacaciones/periodo', views.reporte_vacaciones_periodo, name='reporte.vacaciones.periodo'),
    url(r'^reporte/vacaciones/pendientes', views.reporte_vacaciones_pendientes, name='reporte.vacaciones.pendientes'),
    url(r'^reporte/asignacion-puesto/(\d+)$', views.reporte_asignacion_puesto, name='reporte.asignacion_puesto'),
    url(r'^uaa-puesto/$', views.index_uaa_puesto, name='uaa-puesto.index'),
    url(r'^uaa-puesto/(\d+)$', views.ver_uaa, name='uaa-puesto.ver_uaa'),
    url(r'^uaa-puesto/agregar/funcionario/uaa-puesto/(\d+)$', views.agregar_funcionario_uaa_puesto, name='uaa-puesto.agregar.funcionario.uaa_puesto'),
    url(r'^uaa-puesto/mover/(\d+)$', views.mover_uaa_puesto, name='uaa-puesto.mover_uaa'),
    url(r'^uaa-puesto/inactivar/(\d+)$', views.inactivar_uaa_puesto, name='uaa-puesto.inactivar'),
    url(r'^uaa-puesto/mover/ejecutar/(\d+)/(\d+)$', views.ejecutar_mover_uaa_puesto, name='uaa-puesto.mover_uaa.ejecutar'),
    url(r'^vacaciones/$', views.listar_vacaciones, name='vacaciones.index'),
    url(r'^vacaciones/buscar$', views.buscar_vacaciones, name='vacaciones.buscar'),
    url(r'^vacaciones/detalle/(\d+)$', views.vacaciones_detalle, name='vacaciones.detalle'),
    url(r'^vacaciones/detalle/generar/vacaciones/(\d+)/(\d+)$', views.generar_vacacion_detalle_planificacion, name='vacaciones.detalle.generar.vacaciones'),
    url(r'^vacaciones/detalle/recalcular/(\d+)$', views.recalcular_vacacion, name='vacaciones.detalle.recalcular'),
    url(r'^vacaciones/detalle/recalcular/dias/(\d+)$', views.recalcular_dias_vacacion, name='vacaciones.detalle.recalcular.dias'),
    url(r'^vacaciones/generar$', views.generar_vacaciones, name='vacaciones.generar'),
    url(r'^vacaciones/periodo$', views.periodo_vacaciones, name='vacaciones.periodo'),
    url(r'^vacaciones/periodo/crear$', views.crear_periodo_vacaciones, name='vacaciones.periodo.crear'),
    url(r'^vacaciones/periodo/detalle/eliminar/(\d+)$', views.eliminar_detalle_periodo_vacaciones, name='vacaciones.periodo.detalle.eliminar'),
    url(r'^vacaciones/compensacion/eliminar/(\d+)/(\d+)$', views.eliminar_compensacion_dias, name='vacaciones.compensacion.eliminar'),
    url(r'^vacaciones/registro/eliminar/(\d+)/(\d+)$', views.eliminar_registro_vacacion, name='vacaciones.registro.eliminar'),
    url(r'^vacaciones/reporte_general$', views.reporte_general, name='reporte.vacaciones.registroGeneral'),
    url(r'^reporte/reporte_trayectoria_laboral/(\d+)$', views.trayectoria_laboral_pdf, name='reporte.trayectoria'),
    url(r'^reporte/reporte_vacacion/(\d+)$', views.vacacion_pdf, name='reporte.vacacion'),
    url(r'^reporte/reporte_ausentismos$', views.reporte_ausentismos, name='reporte.ausentismos'),
    url(r'^funcionario/vacacion/lista$', views.vacacion, name='vacacion_lista'),
    url(r'^funcionario/ausentismo/lista$', views.ausentismos, name='ausentismos_lista'),
    ##################
    # Fin de refactorizar
    ##################

    url(r'^asignacion-puesto/filtro-siith$', views.asignacion_puesto_filtro_siith, name='asignacion_puesto_filtro_siith'),

    url(r'^capacitacion/crear/(?P<persona_id>[\d]+)$', views.capacitacion_crear, name='capacitacion_crear'),
    url(r'^capacitacion/editar/(?P<id>[\d]+)$', views.capacitacion_editar, name='capacitacion_editar'),
    url(r'^capacitacion/guardar/(?P<persona_id>[\d]+)$', views.capacitacion_guardar, name='capacitacion_guardar'),
    url(r'^capacitacion/eliminar/(?P<id>[\d]+)$', views.capacitacion_eliminar, name='capacitacion_eliminar'),

    url(r'^declaracion-bienes/crear/(?P<persona_id>[\d]+)$', views.declaracion_bienes_crear, name='declaracion_bienes_crear'),
    url(r'^declaracion-bienes/editar/(?P<id>[\d]+)$', views.declaracion_bienes_editar, name='declaracion_bienes_editar'),
    url(r'^declaracion-bienes/guardar/(?P<persona_id>[\d]+)$', views.declaracion_bienes_guardar, name='declaracion_bienes_guardar'),
    url(r'^declaracion-bienes/eliminar/(?P<id>[\d]+)$', views.declaracion_bienes_eliminar, name='declaracion_bienes_eliminar'),

    url(r'^evaluacion-desempenio/crear/(?P<funcionario_id>[\d]+)$', views.evaluacion_desempenio_crear, name='evaluacion_desempenio_crear'),
    url(r'^evaluacion-desempenio/editar/(?P<id>[\d]+)$', views.evaluacion_desempenio_editar, name='evaluacion_desempenio_editar'),
    url(r'^evaluacion-desempenio/guardar/(?P<funcionario_id>[\d]+)$', views.evaluacion_desempenio_guardar, name='evaluacion_desempenio_guardar'),
    url(r'^evaluacion-desempenio/eliminar/(?P<id>[\d]+)$', views.evaluacion_desempenio_eliminar, name='evaluacion_desempenio_eliminar'),

    url(r'^formacion-academica/senescyt/(?P<persona_id>[\d]+)$', views.formacion_academica_senescyt, name='formacion_academica_senescyt'),
    url(r'^formacion-academica/editar/(?P<id>[\d]+)$', views.formacion_academica_editar, name='formacion_academica_editar'),
    url(r'^formacion-academica/guardar$', views.formacion_academica_guardar, name='formacion_academica_guardar'),
    url(r'^formacion-academica/eliminar/(?P<id>[\d]+)$', views.formacion_academica_eliminar, name='formacion_academica_eliminar'),

    url(r'^informacion-bancaria/crear/(?P<persona_id>[\d]+)$', views.informacion_bancaria_crear, name='informacion_bancaria_crear'),
    url(r'^informacion-bancaria/editar/(?P<id>[\d]+)$', views.informacion_bancaria_editar, name='informacion_bancaria_editar'),
    url(r'^informacion-bancaria/guardar/(?P<persona_id>[\d]+)$', views.informacion_bancaria_guardar, name='informacion_bancaria_guardar'),
    url(r'^informacion-bancaria/eliminar/(?P<id>[\d]+)$', views.informacion_bancaria_eliminar, name='informacion_bancaria_eliminar'),

    url(r'^trayectoria-laboral-externa/crear/(?P<funcionario_id>[\d]+)$', views.trayectoria_laboral_externa_crear, name='trayectoria_laboral_externa_crear'),
    url(r'^trayectoria-laboral-externa/editar/(?P<id>[\d]+)$', views.trayectoria_laboral_externa_editar, name='trayectoria_laboral_externa_editar'),
    url(r'^trayectoria-laboral-externa/guardar/(?P<funcionario_id>[\d]+)$', views.trayectoria_laboral_externa_guardar, name='trayectoria_laboral_externa_guardar'),
    url(r'^trayectoria-laboral-externa/eliminar/(?P<id>[\d]+)$', views.trayectoria_laboral_externa_eliminar, name='trayectoria_laboral_externa_eliminar'),

    url(r'^registro-vacaciones/filtro$', views.registro_vacaciones_filtro, name='registro_vacaciones_filtro'),
    url(r'^registro-vacaciones/reporte$', views.registro_vacaciones_reporte, name='registro_vacaciones_reporte'),

]